Handle nested nils
sermo/deep_slice pull request #2
Opened 2017-10-23 11:37 UTC by sco11morgan

2017-10-23 13:11 UTC, jiacona requested changes
Thanks for the PR. I just have a few comments but will be happy to merge if addressed

2017-10-23 13:11 UTC, jiacona commented on lib/deep_slice.rb
> +                self[sub_key].map { |val|
Might be a bit tidier if written like `val.deep_slice(*[recursive_keys].flatten) unless val.nil?`

2017-10-23 13:11 UTC, jiacona commented on lib/deep_slice.rb
> +                 if self[sub_key].nil?
Same here, I would prefer `self[sub_key].deep_slice(*[recursive_keys].flatten) unless self[sub_key].nil?`

2017-10-23 17:30 UTC, schmidtg commented
:shipit:

2017-10-24 21:59 UTC, sco11morgan commented
@jiacona done

2017-10-25 09:04 UTC, jiacona approved these changes
Looks good! Thanks again for the contribution

2017-10-25 09:13 UTC, jiacona commented
Hah, I just realized I'm not actually a committer on this repo anymore. @schmidtg care to help out?

2017-10-25 17:07 UTC, schmidtg commented
Sure! Thanks @jiacona and @sco11morgan for adding the `nil` option with supported tests.

@sco11morgan , do you mind cleaning up the commits (merge into one commit and write appropriate message for what you're introducing) to keep the git history a little tidier?

Thanks

2017-10-26 01:51 UTC, sco11morgan commented
@schmidtg done.  can you publish the gem after merging?

2017-10-26 19:07 UTC, merged

2017-10-27 09:45 UTC, jiacona commented
@sco11morgan, 0.1.3 is up on rubygems